name: flutter_app_clean_achitecture
description: Flutter application with clean architecture.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Service locator (for dependencies injection)
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^1.0.2
  # Functional programming things and types(like Any, Union in Python as result of function)
  dartz: ^0.8.6

  # Remote APi
  # check if there is internet
  data_connection_checker: ^0.3.4
  # http request
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # for creating mock for testing
  mockito: ^4.1.0


flutter:
  uses-material-design: true